### ISSUE TITLE
wording change to the readme

### ISSUE THREAD

**Issue by moshriguez** [learn-co-curriculum/phase-3-sql-queries#1]
"To select all of the rows from a cats table:" should say "To select all of the **_columns_** from a cats table:"

**Comment by ihollander** [comment]
Thanks for your suggestion! We're going to leave this as it is currently written, because the first example is meant to contrast with the second example, where the `where` clause limits which **rows** are returned by the query:

To select all of the rows from a `cats` table:

```sql
SELECT * FROM cats;
```

To select only rows representing data meeting certain conditions:

```sql
SELECT * FROM cats WHERE name = "Maru";
```
